name : Workflow
on: push

jobs:
  job1-hello:
    runs-on: windows-latest
    steps:
      - name: Imprimir mensagem
        run: echo "Olá, Mundo"
  job2-goodbye:
    runs-on: windows-latest
    steps:
      - name: Step 1 - Sequencia de instruções
        run: |
          echo "Uma nova instrução"
          dir
      - name: Step 2 - Imprimir mensagem
        run: echo "Até logo!"
